---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
```

```{r}
library(skimr)
```


```{r}
pride_aggregates <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_aggregates.csv')
fortune_aggregates <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/fortune_aggregates.csv')
static_list <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/static_list.csv')
pride_sponsors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/pride_sponsors.csv')
corp_by_politicians <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/corp_by_politicians.csv')
donors <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-06-07/donors.csv')


```


```{r}
tuesdata <- tidytuesdayR::tt_load(2022, week = 23)
tuesdata
```


```{r}
corp_by_politicians <-tuesdata$corp_by_politician 
```


```{r paged.print=TRUE}
skim(pride_aggregates)
```


```{r}
data <- pride_aggregates %>% select(Company, `Total Contributed`) %>%  rename(Total = `Total Contributed`)

data <- data 

data <- data[!(data$Company=="Grand Total"),]

data
```

 
```{r}
data %>% slice_max(Total, n = 10)
data %>% slice_min(Total, n = 20) %>% select(Total) %>%  sum()
```
```{r}
#data_v <- data %>% slice_min(Total, n = 30)

# data_v <- data_v %>% add_row(Company = 'Other', Total = 158002.6)
data_v <- data

data_v <- data_v %>% mutate(id = row_number()) 
data_v

```


Standard circular chart with all companies
```{r fig.height=10, fig.width=10}
p <- ggplot(data_v, aes(x = as.factor(id), y = Total/1000))+
  geom_bar(stat = 'identity', fill = alpha('skyblue', 0.7)) + 
  ylim(-250,620) +
  theme_minimal(base_family = "Roboto Condensed") +
  theme(
    axis.text = element_blank(),
    #axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
  ) +
  coord_polar(start = 0)

  # This makes the coordinate polar instead of cartesian.
  

p
```


```{r}
label_data <- data_v
 
# calculate the ANGLE of the labels
number_of_bar <- nrow(label_data)
angle <-  90- 360 * (label_data$id-0.5) /number_of_bar     

# I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
 
# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
label_data$hjust<-ifelse( angle < -90, 1, 0)
 
# flip angle BY to make them readable
label_data$angle<-ifelse(angle < -90, angle+180, angle)
```

```{r}
#install.packages('gghighlight')
library(gghighlight)
```

```{r fig.height=12, fig.width=12}
p + 
  gghighlight(Total > 100000) + 
  geom_text(data=label_data, aes(x=id, y=Total/1000, label=Company, hjust=hjust), color="black",  fontface="bold", alpha=0.6, size=5, angle= label_data$angle, inherit.aes = FALSE, family = 'Roboto Condensed') +
  labs(title = 'A cool title',
       caption = 'CAPTION') +
  theme(plot.title = element_text(face = 'bold', size = 50),
        plot.title.position = 'plot',
        plot.caption = element_text(hjust=0, color="grey20", size=9),
        plot.margin=margin(.34,1.4,.3,.4, unit="cm") 
        )+
 geom_text(
    x = 110, y = -280,
    label = tmp,
    family = "Roboto Mono Medium",
    size = 11,
    lineheight = 0.87,
    color = "#483D8B"
  ) +
  geom_text(
    x = 230, y = -280,
    label = "ALLIES?",
    family = "Roboto Mono Medium",
    size = 11,
    lineheight = 0.87,
    color = "#483D8B"
  )
  
```



```{r}
strk <- stringr::str_replace_all("ANTI  ", "(?<=.)", "\u0336")
strk
```

```{r}
tmp <- cbind(strk, "LGBT ALLIES?")

tmp <- str_c(tmp, collapse = "")

tmp
```

```{r}
data_v
```



```{r fig.height=10, fig.width=10}
p <- ggplot(data_v, aes(x = as.factor(id), y = Total/1000))+
  geom_bar(stat = 'identity', fill = alpha('lightgoldenrod', 0.7)) + 
  theme_minimal(base_family = "AvantGarde") +
  theme(
    axis.text = element_blank(),
    #axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
  ) +
  coord_polar(start = 0)


p + 
  gghighlight(Total > 100000) + 
  geom_text(data=label_data, aes(x=id, y=Total/1000, label=Company, hjust=hjust), color="navy",  fontface="bold", alpha=0.6, size=5, angle= label_data$angle, inherit.aes = FALSE, family = 'Roboto Condensed') +
  labs(title = tmp,
       subtitle = "Toyota Dominates Donations To ANTI-LGBT\nIn Ranks of Pride Supporters. kUSD",
       caption = "TidyTuesday W24 | Source: Data For Progress | @TimurZolkin") +
  theme(plot.title = element_text(face = 'bold', size = 40),
        plot.subtitle = element_text(face = "bold", size = 20),
        plot.title.position = 'plot',
        plot.caption = element_text(hjust=1, color="grey20", size=10, vjust = 20),
        plot.margin=margin(.34,1.4,.3,.4, unit="cm"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()
        )+
  scale_y_continuous(
    limits = c(-250, 650),
    breaks = c(0, 300, 600)
  ) +
  geom_text(aes(label = round(Total/1000,0) ), hjust = 1, vjust = 1.5, nudge_x = .2, size = 4, colour = "black",fontface = "bold" )
  
```

```{r fig.height=10, fig.width=10}
p <- ggplot(data_v, aes(x = as.factor(id), y = Total/1000))+
  geom_bar(stat = 'identity', fill = alpha('lightgoldenrod', 0.7)) + 
  theme_minimal(base_family = "AvantGarde") +
  theme(
    axis.text = element_blank(),
    #axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
  ) +
  coord_polar(start = 0)


p_final <- p + 
  gghighlight(Total > 100000) + 
  geom_text(data=label_data, aes(x=id, y=Total/1000, label=Company, hjust=hjust), color="darkorchid4",  fontface="bold", alpha=0.6, size=5, angle= label_data$angle, inherit.aes = FALSE, family = 'Roboto Condensed') +
  labs(title = tmp,
       subtitle = "Toyota Dominates Donations To ANTI-LGBT\nIn Ranks of Pride Supporters\n(KUSD)",
       caption = "TidyTuesday Week 23 | Source: Data For Progress | @TimurZolkin") +
  theme(plot.title = element_text(face = 'bold', size = 40, color = "firebrick"),
        plot.subtitle = element_text(face = "bold", size = 20, color = "grey20"),
        plot.title.position = 'plot',
        plot.caption = element_text(hjust=1, color="grey20", size=10, vjust = 20),
        plot.margin=margin(.34,1.4,.3,.4, unit="cm"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()
        )+
  scale_y_continuous(
    limits = c(-250, 650),
    breaks = c(0, 300, 600)
  ) +
  geom_text(aes(label = round(Total/1000,0) ), hjust = 1, vjust = 1.5, nudge_x = .2, size = 4, colour = "black",fontface = "bold" )

p_final
```


```{r fig.height=10, fig.width=10}
png("TidyTuesday W23.png")
print(p_final)
dev.off()
```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```